import { Project, ArtPiece } from './types';

export const DESIGN_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'TICCIT Educational Campaign',
    category: 'Campaign Design',
    imageUrl: '/assets/projects/Studek_TICCIT.webp',
    description: 'A dedicated educational campaign focusing on environmental sustainability and creative learning.',
    year: '2024',
    orientation: 'landscape',
    client: 'TICCIT Program',
    deliverables: ['Social Media Assets', 'Educational Posters', 'Presentation Deck'],
    tools: ['Photoshop'],
  },
  {
    id: '2',
    title: 'UMKM Empowerment Platform',
    category: 'Digital Branding',
    imageUrl: '/assets/projects/Final_bannerSlider_linkUMKM.webp',
    description: 'Visual identity and slider design for a platform connecting local SMEs with broader markets.',
    year: '2023',
    orientation: 'landscape',
    client: 'LinkUMKM',
    deliverables: ['Web Banner', 'Slider Design', 'Visual Hierarchy'],
    tools: ['Photoshop'],
  },
  {
    id: '3',
    title: 'LDK Organization Identity',
    category: 'Branding',
    imageUrl: '/assets/projects/Final FG LDK_1.webp',
    description: 'Clean and professional branding for a student organization, focusing on leadership and community.',
    year: '2023',
    orientation: 'square',
    client: 'LDK Organization',
    deliverables: ['Logo System', 'Visual Identity', 'Event Materials'],
    tools: ['Illustrator'],
  },
  {
    id: '4',
    title: 'Qurban Collection & Distribution',
    category: 'Organization Branding',
    imageUrl: '/assets/projects/Banner Qurban fix.webp',
    description: 'A strategic communication banner for LDK FIKRI PNJ & DKM PNJ to facilitate the collection and distribution of Qurban animals within the campus community.',
    year: '2024',
    orientation: 'landscape',
    client: 'LDK FIKRI PNJ & DKM PNJ',
    deliverables: ['Information Banner', 'Visual Communication'],
    tools: ['Photoshop'],
  },
  {
    id: '5',
    title: 'Darul Ilmi Qurban Campaign',
    category: 'Event Campaign',
    imageUrl: '/assets/projects/Poster Qurban PNJ DKM3.webp',
    description: 'A compelling invitation and pricing guide for the Qurban initiative at Masjid Darul Ilmi PNJ, featuring a detailed breakdown for joint-offering (patungan) participants.',
    year: '2024',
    orientation: 'portrait',
    client: 'Masjid Darul Ilmi PNJ',
    deliverables: ['Campaign Poster', 'Pricing Graphics'],
    tools: ['Photoshop'],
  },
  {
    id: '6',
    title: 'Ramadhan Festive Branding',
    category: 'Event Branding',
    imageUrl: '/assets/projects/Banner Ramadhan_final.webp',
    description: 'Vibrant and festive visual system for Ramadhan seasonal marketing and greetings.',
    year: '2023',
    orientation: 'landscape',
    client: 'LinkUMKM BRI SEI',
    deliverables: ['Seasonal Banner', 'Social Assets'],
    tools: ['Photoshop'],
  },
  {
    id: '7',
    title: 'Female Mascot Banner',
    category: 'Character Design',
    imageUrl: '/assets/projects/female mascott banner.webp',
    description: 'A vibrant banner design featuring a custom female mascot, tailored for brand engagement.',
    year: '2024',
    orientation: 'landscape',
    client: 'LDK FIKRI',
    deliverables: ['Mascot Design', 'Banner Layout'],
    tools: ['Procreate'],
  },
  {
    id: '8',
    title: 'Male Mascot Banner',
    category: 'Character Design',
    imageUrl: '/assets/projects/male mascott banner.webp',
    description: 'A dynamic banner design showcasing a custom male mascot for marketing and promotional use.',
    year: '2024',
    orientation: 'landscape',
    client: 'LDK FIKRI',
    deliverables: ['Mascot Design', 'Banner Layout'],
    tools: ['Procreate'],
  },
  {
    id: '9',
    title: 'Business Capital Loan Banner',
    category: 'Digital Promotion',
    imageUrl: '/assets/projects/Banner Pinjaman Butuh Modal.jpg',
    description: 'A professional promotional banner for business capital loans, designed for LinkUMKM applications.',
    year: '2023',
    orientation: 'landscape',
    client: 'BPR HANEDA',
    deliverables: ['Promotional Banner', 'Typography Design'],
    tools: ['Photoshop'],
  }
];

export const ART_GALLERY: ArtPiece[] = [
  {
    id: 'a1',
    title: 'Three Guardians',
    imageUrl: '/assets/arts/3 Pandas.webp',
    medium: 'Digital Illustration',
    quote: "Unity in diversity, represented by three spirits of nature.",
    timeSpent: "14 Hours",
    dimensions: "3000 x 4000px"
  },
  {
    id: 'a2',
    title: 'Duality of Self',
    imageUrl: '/assets/arts/A Half 3.webp',
    medium: 'Digital Art',
    quote: "Exploring the layers of personality through split visuals.",
    timeSpent: "8 Hours",
    dimensions: "2000 x 2000px"
  },
  {
    id: 'a3',
    title: 'The Silent Town',
    imageUrl: '/assets/arts/A Quite Town.webp',
    medium: 'Concept Art',
    quote: "Peace found in the absence of noise. A study of atmospheric light.",
    timeSpent: "20 Hours",
    dimensions: "5000 x 3000px"
  },
  {
    id: 'a4',
    title: 'Eternal Autumn',
    imageUrl: '/assets/arts/Autumn 4.webp',
    medium: 'Digital Painting',
    quote: "Capturing the fleeting warmth before the winter cold.",
    timeSpent: "25 Hours",
    dimensions: "4000 x 6000px"
  },
  {
    id: 'a5',
    title: 'Grizzly Spirit',
    imageUrl: '/assets/arts/Bear3.webp',
    medium: 'Digital Sketch',
    quote: "Strength and silence in the wild.",
    timeSpent: "6 Hours",
    dimensions: "2500 x 2500px"
  },
  {
    id: 'a6',
    title: 'Eastern Heritage',
    imageUrl: '/assets/arts/Chinese Girl Fix.webp',
    medium: 'Digital Portrait',
    quote: "A modern take on traditional cultural motifs.",
    timeSpent: "18 Hours",
    dimensions: "3500 x 4500px"
  },
  {
    id: 'a7',
    title: 'Woodland Sanctuary',
    imageUrl: '/assets/arts/Forest House.webp',
    medium: 'Environment Design',
    quote: "A home where the trees are the only neighbors.",
    timeSpent: "30 Hours",
    dimensions: "6000 x 4000px"
  },
  {
    id: 'a8',
    title: 'Frost Glare',
    imageUrl: '/assets/arts/Girl with cold glare Finish2.webp',
    medium: 'Digital Character Art',
    quote: "A look that pierces through the winter soul.",
    timeSpent: "12 Hours",
    dimensions: "3000 x 4000px"
  },
  {
    id: 'a9',
    title: 'Ancient Relic',
    imageUrl: '/assets/arts/Killer Axe.webp',
    medium: '3D Render / Paint',
    quote: "Every scratch tells a story of a battle won.",
    timeSpent: "15 Hours",
    dimensions: "2000 x 3000px"
  },
  {
    id: 'a10',
    title: 'Summit Silence',
    imageUrl: '/assets/arts/Mountain 0.webp',
    medium: 'Matte Painting',
    quote: "The air is thin, but the view is endless.",
    timeSpent: "22 Hours",
    dimensions: "8000 x 4000px"
  },
  {
    id: 'a11',
    title: 'The Crossroads',
    imageUrl: '/assets/arts/Stay Or Leave.webp',
    medium: 'Mixed Media',
    quote: "Every choice creates a new universe.",
    timeSpent: "10 Hours",
    dimensions: "3000 x 3000px"
  },
  {
    id: 'a12',
    title: 'Forgotten Hero',
    imageUrl: '/assets/arts/wasted warrior.webp',
    medium: 'Digital Sketch',
    quote: "Rest comes to those who served with honor.",
    timeSpent: "7 Hours",
    dimensions: "2500 x 3500px"
  },
  {
    id: 'a13',
    title: 'Eternally Yours',
    imageUrl: '/assets/arts/Eternally Yours.webp',
    medium: 'Digital Illustration',
    quote: "A bond that transcends time and space.",
    timeSpent: "16 Hours",
  },
  {
    id: 'a14',
    title: 'Rest in love, My Sweety',
    imageUrl: '/assets/arts/Rest in love, My Sweety.jpeg',
    medium: 'Digital Art',
    quote: "A peaceful parting, filled with love.",
    timeSpent: "5 Hours",
  },
  {
    id: 'a15',
    title: 'Together',
    imageUrl: '/assets/arts/Together.webp',
    medium: 'Digital Art',
    quote: "The strength found in unity.",
    timeSpent: "12 Hours",
  },
  {
    id: 'a16',
    title: 'Xing Hai',
    imageUrl: '/assets/arts/Xing Hai.webp',
    medium: 'Digital Art',
    quote: "Navigating the celestial sea.",
    timeSpent: "20 Hours",
  },
  {
    id: 'a17',
    title: 'Zzz',
    imageUrl: '/assets/arts/Zzz.jpeg',
    medium: 'Digital Sketch',
    quote: "Finding peace in the quiet moments of rest.",
    timeSpent: "4 Hours",
  },
  {
    id: 'a18',
    title: 'A Cup of Bunny',
    imageUrl: '/assets/arts/a cup of bunny.webp',
    medium: 'Digital Illustration',
    quote: "A small dose of cuteness to start the day.",
    timeSpent: "8 Hours",
  },
  {
    id: 'a19',
    title: 'Abstract Portrait',
    imageUrl: '/assets/arts/abstract potrait.webp',
    medium: 'Abstract Art',
    quote: "Exploring identity through unconventional forms.",
    timeSpent: "10 Hours",
  },
  {
    id: 'a20',
    title: 'Girl with Peachy Eyes',
    imageUrl: '/assets/arts/girl with peachy eyes.webp',
    medium: 'Digital Portrait',
    quote: "A gaze that holds the warmth of soft light.",
    timeSpent: "14 Hours",
  },
  {
    id: 'a21',
    title: 'Halloween Pumpkin',
    imageUrl: '/assets/arts/halloween Pumpkin.webp',
    medium: 'Digital Illustration',
    quote: "The spooky charm of autumn nights.",
    timeSpent: "7 Hours",
  },
  {
    id: 'a22',
    title: 'Impressionist Study',
    imageUrl: '/assets/arts/impressionist.webp',
    medium: 'Digital Painting',
    quote: "Capturing the essence through rapid strokes and light.",
    timeSpent: "18 Hours",
  },
  {
    id: 'a23',
    title: 'Lazy Portrait',
    imageUrl: '/assets/arts/lazy potrait.webp',
    medium: 'Digital Art',
    quote: "The beauty of unstructured time and relaxed moments.",
    timeSpent: "9 Hours",
  },
  {
    id: 'a24',
    title: 'Love at First Sight',
    imageUrl: '/assets/arts/love at the first sight.jpeg',
    medium: 'Digital Art',
    quote: "The moment everything changed.",
    timeSpent: "11 Hours",
  },
  {
    id: 'a25',
    title: 'With You',
    imageUrl: '/assets/arts/with you.webp',
    medium: 'Digital Illustration',
    quote: "Every moment is better when shared.",
    timeSpent: "15 Hours",
  }
];